server:
  port: 6090

spring:
  cloud:
    gateway:
      routes:
        - id: product_api
          uri: http://localhost:6081/
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/, /product/
        - id: category_api
          uri: http://localhost:6092/
          predicates:
            - Path=/api/category/**
          filters:
            - RewritePath=api/category/, /category/