server:
  port: 5092
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rs_ecommerce?useSSL=false
    username: root
    password: root
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
  template:
    cache: false

management:
  server:
    port: 5093
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"